name: Build and Deploy reporting-func-v2 Service to Cloud Run
on: 
  push:
     branches:
     - main
     paths:
      - reporting-func-v2/**

env:
  PROJECT_ID: ${{secrets.GCP_PROJECT}}
  SERVICE: reporting-func-v2
  REGION: ${{secrets.GCP_DEFAULT_REGION}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: set defaults
      run: |-
        echo $PROJECT_ID
        echo $REGION
        gcloud config set project $PROJECT_ID
        gcloud config set run/platform managed
        gcloud config set run/region $REGION
    - name: Authorize Docker push
      run: gcloud auth configure-docker
    - name: Build and Push Container
      run: |-
        cd $SERVICE
        ./build-and-deploy-service.sh
        
    

   
