name: Build and Deploy Trigger Func to Cloud Run
on: workflow_dispatch
  # push:
  #   branches:
  #   - example

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: trigger-func
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: set defaults
      run: |-
        gcloud config set project $PROJECT_ID
        gcloud config set run/platform managed
        gcloud config set run/region us-central1
    - name: Authorize Docker push
      run: gcloud auth configure-docker
    - name: Build and Push Container
      run: |-
        cd $SERVICE
        ./build-and-deploy-service.sh
        
    

   
